### ISSUE TITLE
Requires excessive amounts of RAM

### ISSUE THREAD

**Issue by PoroCYon** [vsariola/zebrain#1]
Not everyone has 128G of RAM.

```
>> zebrain
Requested 17094516516x1 (127.4GB) array exceeds maximum array size preference. Creation of arrays greater than this limit may take a long time and cause MATLAB to become
unresponsive. See array size limit or preference panel for more information.
```

After disabling the limit in the preferences:

```
>> zebrain
Out of memory. Type "help memory" for your options.
```

Seems to happen both on an Ubuntu 18.04.3 LTS server (running via X11 forwarding) with 16G RAM & 8G swap, as well as noby's 32G Windows box.

Also the screen is 1366x768 so that can't be causing the "high memory usage on 4K screens" I think.

**Comment by armak** [comment]
I have the same issue. MATLAB R2019b (latest version I think, just installed) on Windows 10 1903 64-bit.

**Comment by PoroCYon** [comment]
I also tried building it and running the `.m` file instead, with the same result.

EDIT: this seems to happen on line 51 (`k = [(0:a-1)/a,ones(1,q(12)^2 * 4),1-(0:K-1)/K];`), i.e. [here](https://github.com/vsariola/zebrain/blob/master/src/player.m#L49).

EDIT2: `attack=1.7095e+10, release=6.8378e+10, instrparams(12)=65373`. This feels... wrong.

**Comment by vsariola** [comment]
This is it then. On my computer, strings give character values 0 - 255. How 65373 gets there is a mystery. Can you either try the branch [fix/songdata_in_arrays](/vsariola/zebrain/tree/fix/songdata_in_arrays) (remember to run `generate_song.m` before `demo.m`! otherwise `song.m` does not get recreated). Alternatively, download this single-file, but unminified version:

https://drive.google.com/file/d/1OEFRAoG9P84PWxQHfCwRlNAwur8L6V5Z/view?usp=sharing

If this works, I'll add a version to the archival package that does not use strings; it probably won't fit into 4k, but that's probably better than not watching at all.

**Comment by vsariola** [comment]
Breakthrough: I am able to replicate the issue on my computer. It appears when the 'DefaultCharacterSet' is 'UTF8' instead of 'windows-1252'.

Quick fix is to run `feature('DefaultCharacterSet','windows-1252')` before starting the demo. To revert the setting, run `feature('DefaultCharacterSet','UTF8')`.

I'll try to figure a more permanent solution.

**Comment by armak** [comment]
This resolves the problem on my end =)

**Comment by PoroCYon** [comment]
Works here, too.

Maybe instead of using normal arrays, base64-encoded data could be an option? (But this doesn't compress as well as raw binary data, of course.)

Or, you could append the raw data after the end of the file, then make the script read itself, seek past the actual code and read the data? (Like shell script unpackers for Linux 4ks.)

EDIT: or just encode it in 7 bits/byte to stay in the ASCII range.
